services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: codetrust
      POSTGRES_PASSWORD: codetrust
      POSTGRES_DB: codetrust
    ports:
      - "5432:5432"
    volumes:
      - codetrust_pg:/var/lib/postgresql/data

volumes:
  codetrust_pg:
